export const ASYNC_GET_CATS = 'ASYNC_GET_CATS';
export const FAILURE_GET_CATS = 'FAILURE_GET_CATS';
export const SUCCESS_GET_CATS = 'SUCCESS_GET_CATS';

export const SELECT_CAT = 'SELECT_CAT';

export const ASYNC_GET_BREEDS = 'ASYNC_GET_BREEDS';
export const FAILURE_GET_BREEDS = 'FAILURE_GET_BREEDS';
export const SUCCESS_GET_BREEDS = 'SUCCESS_GET_BREEDS';

export const SELECT_BREED = 'SELECT_BREED';

export const TOGGLE_BREEDS_MENU = 'TOGGLE_BREEDS_MENU';
