export const SELECT_BREED = 'SELECT_BREED';
export const ASYNC_GET_BREEDS = 'ASYNC_GET_BREEDS';
export const SUCCESS_GET_BREEDS = 'SUCCESS_GET_BREEDS';
export const FAILURE_GET_BREEDS = 'FAILURE_GET_BREEDS';
